require "erb"
require "fileutils"
require "optparse"
require "terminal-table"

require "file_templater/variables"
require "file_templater/template"
require "file_templater/file_actions"
require "file_templater/options_handler"
require "file_templater/bindings"
